// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agolyfrptydlbxdcsqvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnb2x5ZnJwdHlkbGJ4ZGNzcXZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzgzMjIsImV4cCI6MjA3Mjc1NDMyMn0._RS1ddTseBV-Qelqmk1d4LAPk4n-F2OIKE07fBhX69o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});